image:
  repository: "942010118414.dkr.ecr.us-east-2.amazonaws.com/app-repository"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

deployment:
  replicaCount: 1
  containerPort: 5000

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
